// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"context"
	"github.com/urfave/cli/v3"
	"wallet/api"
	"wallet/api/grpc"
	"wallet/internal/repository/wallet"
	wallet2 "wallet/internal/service/wallet"
)

// Injectors from wire.go:

func InitializeApplication(c *cli.Command, appCtx context.Context) (api.Container, error) {
	config := provideGRPCServerConfig(c)
	accountStore := wallet.NewStore()
	walletService := wallet2.NewService(accountStore)
	resolver := grpc.NewResolver(config, walletService)
	container := api.NewContainer(resolver)
	return container, nil
}
